#!/usr/bin/env bash
set -euo pipefail

# Patch Unity project for CI compatibility
# Removes Tuanjie Engine specific packages and fixes version number

PROJECT_DIR="${1:-.}"

echo "[CI Patch] Patching project for standard Unity CI..."

# 1. Fix ProjectVersion.txt: 2022.3.61t14 -> 2022.3.48f1
VERSION_FILE="$PROJECT_DIR/ProjectSettings/ProjectVersion.txt"
if [ -f "$VERSION_FILE" ]; then
    sed -i 's/2022\.3\.61t14/2022.3.48f1/g' "$VERSION_FILE"
    sed -i '/m_TuanjieEditorVersion/d' "$VERSION_FILE"
    echo "[CI Patch] ProjectVersion.txt patched to standard Unity 2022.3.48f1"
fi

# 2. Remove Tuanjie-specific packages from manifest.json
MANIFEST_FILE="$PROJECT_DIR/Packages/manifest.json"
if [ -f "$MANIFEST_FILE" ]; then
    cp "$MANIFEST_FILE" "$MANIFEST_FILE.bak"
    python3 -c "
import json
with open('$MANIFEST_FILE', 'r') as f:
    manifest = json.load(f)

# Packages to remove: Tuanjie-specific, MCP, and modules not in standard Unity
remove_prefixes = ('cn.tuanjie',)
remove_exact = {
    'com.coplaydev.unity-mcp',
    'com.unity.modules.infinity',
}

removed = []
for key in list(manifest['dependencies'].keys()):
    if any(key.startswith(p) for p in remove_prefixes) or key in remove_exact:
        del manifest['dependencies'][key]
        removed.append(key)

# Also clean testables if any reference removed packages
if 'testables' in manifest:
    manifest['testables'] = [
        t for t in manifest['testables']
        if not any(t.startswith(p) for p in remove_prefixes) and t not in remove_exact
    ]

with open('$MANIFEST_FILE', 'w') as f:
    json.dump(manifest, f, indent=2)

print(f'[CI Patch] Removed {len(removed)} packages: {', '.join(removed)}')
"
fi

# 2b. Add Code Coverage package for coverage job
if [ -f "$MANIFEST_FILE" ]; then
    python3 -c "
import json
with open('$MANIFEST_FILE', 'r') as f:
    manifest = json.load(f)

# Add code coverage package if not present
if 'com.unity.testtools.codecoverage' not in manifest['dependencies']:
    manifest['dependencies']['com.unity.testtools.codecoverage'] = '1.2.5'
    print('[CI Patch] Added com.unity.testtools.codecoverage package')
else:
    print('[CI Patch] Code coverage package already present')

with open('$MANIFEST_FILE', 'w') as f:
    json.dump(manifest, f, indent=2)
"
fi

# 3. Delete packages-lock.json so Unity regenerates it with resolved deps
LOCK_FILE="$PROJECT_DIR/Packages/packages-lock.json"
if [ -f "$LOCK_FILE" ]; then
    rm "$LOCK_FILE"
    echo "[CI Patch] Deleted packages-lock.json (will be regenerated by Unity)"
fi

echo "[CI Patch] Done. Project is now compatible with standard Unity 2022.3 LTS."
